version: '2'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7.29
    hostname: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: tracks
      MYSQL_user: dmarzin
      MYSQL_password: P@ssw0rd
    volumes:
      - /home/dmarzin/compose/db-data:/var/lib/mysql
  web:
    container_name: tracks
    build: /home/dmarzin/Tracks_In_Docker
    volumes:
      - /home/dmarzin/compose/web:/app}
    ports:
      - 3000:3000
    depends_on:
      - mysql
  tracks_sa:
    container_name: tracks_sa
    build: /home/dmarzin/Tracks_In_Docker
    volumes:
      - /home/dmarzin/compose/web:/app}
    ports:
      - 3000:3000
